<a href="https://colab.research.google.com/github/chuangchai49097/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # package สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

###สร้าง matrix เริ่มต้น (zeros, ones)

In [6]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##สร้าง matrix random

In [9]:
np.random.randn(5,5) # random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.90378124,  1.06544588, -0.68846159, -0.98366112, -0.24095976],
       [ 0.41269053, -2.01347329,  1.81328193, -1.2797014 , -0.55185153],
       [-1.66673115,  0.58433576,  0.31016778,  0.1067368 ,  0.60686595],
       [-0.67537702,  1.39031935, -0.32262948, -1.30573822, -1.08325218],
       [-1.38460823, -1.84632766, -0.99207284,  1.28516056,  0.38445177]])

In [10]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ 6.47292422,  2.74314615, 16.97748244],
       [-5.48337713, -3.94742679,  3.67676457],
       [ 2.88389414, 12.97729371, 11.74618812]])

In [11]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ระหว่าง [5,11) ขนาด (4x5)

array([[ 7,  9,  7,  8,  6],
       [ 5,  6,  6,  5,  5],
       [10,  6,  8,  8,  7],
       [ 8,  7,  6,  8,  7]])

##matrix properties

In [12]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:

np_a.T  #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
1 + np_a  #adding scalar to matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
2 * np_a  #multipling scalar to matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [16]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [17]:
np_a + np_c  #adding matrix to matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [18]:
np_a.shape

(2, 3)

In [19]:
np_c.shape

(2, 3)

In [20]:
np_c.T.shape

(3, 2)

In [21]:
np.dot(np_a,np_c.T)  #multipling matrix to matrix   (a,b) x (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

##Indexing & Slicing

In [22]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np_a[1,1]

5

In [24]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [25]:
np_a[0,:]

array([1, 2, 3])

##Useful functions

In [26]:

np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.sum(np_a)

21

In [28]:
np.sum(np_a,axis=0)  # axis 0 ก็คือรวมเลขในแต่ละแถว

array([5, 7, 9])

In [29]:
np.sum(np_a,axis=1)  # axis 1 ก็คือรวมเลขในแต่ละหลัก

array([ 6, 15])

In [30]:
np.mean(np_a)

3.5

In [31]:
np.mean(np_a,axis=0)  #หา mean ของ column

array([2.5, 3.5, 4.5])

##วนลูปเอง

**summation**

In [32]:
np_a.shape

(2, 3)

np.sum(np_a)

In [34]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]}  sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1  sum_all=1
we are at row=0,col=1 np_a[0,1]=2  sum_all=3
we are at row=0,col=2 np_a[0,2]=3  sum_all=6
we are at row=1,col=0 np_a[1,0]=4  sum_all=10
we are at row=1,col=1 np_a[1,1]=5  sum_all=15
we are at row=1,col=2 np_a[1,2]=6  sum_all=21
21


np.sum(np_a,axis=0)

In [35]:

sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


[5. 7. 9.]
Quiz กลุ่ม

วนลูปหาค่า

np.sum(np_a,axis=1) sukuna /

np.mean(np_a) i love อ.ต้น /

np.mean(np_a,axis=0) natashar /

np.mean(np_a,axis=1) teletubby /

np.max(np_a) numba one /

np.max(np_a,axis=0) เอกาไร้สติ /

np.max(np_a,axis=1) sandbox /

np.min(np_a) ลูกหมี /

np.min(np_a,axis=0) wakame /

np.min(np_a,axis=1) แมวส้ม /

In [36]:

# np.max(np_a,axis=1)
max_all = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
    max_all[row] = max(np_a[row,:])
print(max_all)

[3. 6.]


In [37]:
#np.mean(np_a,axis=0)
mean_all = np.zeros(np_a.shape[1])
for row in range(np_a.shape[0]):
     for col in range(np_a.shape[1]):
          mean_all[col] = mean_all[col] + np_a[row,col]/np_a.shape[0]
print(mean_all)

[2.5 3.5 4.5]


In [38]:
#np.mean(np_a,axis=1)
sum_all = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]): 
        sum_all[row] = sum_all[row] + np_a[row,col]
sum_all = sum_all/np_a.shape[1]
print(sum_all)

[2. 5.]


In [39]:
#np.max(np_a)
max_a = -100000000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] > max_a :
            max_a = np_a[row,col]
print(max_a)

6


In [40]:
### 10. np.min(np_a,axis=1)
min_row = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
   min_row[row] = min(np_a[row,:])
print(min_row)

[1. 4.]


In [41]:
# np.min(np_a,axis=0)
min_all = np.zeros(np_a.shape[1])

for col in range(np_a.shape[1]):
    min_all[col] = min(np_a[:,col])
print(min_all)

[1. 2. 3.]


In [42]:
# np.min(np_a)  ลูกหมี
minV = 100000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] < minV:
            minV = np_a[row,col]
print(minV)

1


In [43]:
# np.max(np_a,axis=0)
max_all = -100000 * np.ones(np_a.shape[1])
for col in range(np_a.shape[1]):
    for row in range(np_a.shape[0]):
        if np_a[row,col] > max_all[col]: 
            max_all[col] = np_a[row,col]
print(max_all)

[4. 5. 6.]


In [44]:

#np.mean(np_a)
mean_all = 0
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        mean_all = mean_all + np_a[row,col]
mean_all = mean_all/(np_a.shape[0]*np_a.shape[1])
print(mean_all)

3.5
